#!/bin/bash
wget -O splunk-8.1.1-08187535c166-linux-2.6-amd64.deb 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.1.1&product=splunk&filename=splunk-8.1.1-08187535c166-linux-2.6-amd64.deb&wget=true'
sudo dpkg -i splunk-8.1.1-08187535c166-linux-2.6-amd64.deb
export SPLUNK_HOME=/opt/splunk/
sudo $SPLUNK_HOME/bin/splunk start --accept-license
#enter username and password after
